name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps

      - name: Regenerate Prisma Client
        run: pnpm prisma generate

      - name: Run Playwright tests
        run: pnpm playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
