name: Vitest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: "file:./db.sqlite"
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Seed The Database
        run: pnpm db:push && pnpm prisma db seed

      - name: Run Vitest Tests
        run: pnpm vitest --run
